<?php

namespace Exzachlyvv\LaravelLearn\Tests;

use Exzachlyvv\LaravelLearn\LaravelLearnServiceProvider;
use Illuminate\Support\Facades\Http;
use Orchestra\Testbench\TestCase as Orchestra;

class BaseTest extends Orchestra
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadMigrationsFrom(__DIR__ . '/Models/migrations');
    }

    protected function getPackageProviders($app)
    {
        return [LaravelLearnServiceProvider::class];
    }
}
